### ISSUE TITLE
Saving image fails if the image path includes whitespaces

### ISSUE THREAD

**Issue by Muhammed-Rahif** [freshtechtips/gal-linux#2]
I was using `flutter_quill`, and when saving image file on `flutter_quill`, this occurs.

Flutter output:
```
flutter: mkdir -p /tmp/gal
flutter: mv /home/username/Pictures/Sample Image.png /tmp/gal/2024-02-28T07:19:10.186786-Sample Image.png
flutter: Process exception, mv: target 'Image.png': No such file or directory
```

I have tried running the exact command like below and its works. 
```bash
mv "/home/username/Pictures/Sample Image.png" "/tmp/gal/2024-02-28T07:19:10.186786-Sample Image.png"
```

And its better to use `cp` for saving file that it saves copy of the file rather than moving it. Because flutter quill doesn't exactly say where the image file has been saved. So for the end users it will be hard to them to find it on `/tmp/gal/`. Maybe I should create a issue on flutter quill repo.

**Comment by Muhammed-Rahif** [comment]
Moving the file makes an `Execption: Asset not found` error in flutter quill, after restarting the app.

**Comment by EchoEllet** [comment]
This issue should be fixed in this [commit](https://github.com/ellet0/gal-linux/commit/3d52ab1aed7c4f5c077791d0f732e80d9ba78d3e)

Please confirm if it's fixed or not to move to the next issue

**Comment by Muhammed-Rahif** [comment]
@ellet0 So the problem was not resolved, I wondered why. After a long time of digging through the code I finally found that the problems causes from https://github.com/ellet0/gal-linux/blob/3d52ab1aed7c4f5c077791d0f732e80d9ba78d3e/lib/src/utils/command_line.dart#L11

The splitting of whitespaces causes the issue on variable `args`. The file path `/home/username/Pictures/Sample Image.jpg` will be concidered as two files. For more understanding:
```diff
- args = ["/home/username/Pictures/Sample" "Image.jpg"]
+ args = ["/home/username/Pictures/Sample Image.jpg"]
```

So, now we have to revert the https://github.com/ellet0/gal-linux/commit/3d52ab1aed7c4f5c077791d0f732e80d9ba78d3e commit. And to fix the `executeCommand` function, we should not split it on whitespaces. Maybe we have to do the dart intended way by passing the argument as list.

**Comment by Muhammed-Rahif** [comment]
And when saving the image file, it should use `cp` (copying) rather than `mv` (moving), because currently, the image from the editor disappears after save and it will throw an 'asset not found' error.

**Comment by ellet0** [comment]
> And when saving the image file, it should use `cp` (copying) rather than `mv` (moving), because currently, the image from the editor disappears after save and it will throw an 'asset not found' error.

I'm late but
- can you check this #3

test the branch changes locally and see if the issue is still there, I don't have access to my Linux machine right now so I can't manually test it, since the package is relatively small I might write tests in the future

**Comment by EchoEllet** [comment]
> @ellet0 So the problem was not resolved, I wondered why. After a long time of digging through the code I finally found that the problems causes from
> 
> https://github.com/ellet0/gal-linux/blob/3d52ab1aed7c4f5c077791d0f732e80d9ba78d3e/lib/src/utils/command_line.dart#L11
> 
> The splitting of whitespaces causes the issue on variable `args`. The file path `/home/username/Pictures/Sample Image.jpg` will be concidered as two files. For more understanding:
> 
> ```diff
> - args = ["/home/username/Pictures/Sample" "Image.jpg"]
> + args = ["/home/username/Pictures/Sample Image.jpg"]
> ```
> 
> So, now we have to revert the [3d52ab1](https://github.com/ellet0/gal-linux/commit/3d52ab1aed7c4f5c077791d0f732e80d9ba78d3e) commit. And to fix the `executeCommand` function, we should not split it on whitespaces. Maybe we have to do the dart intended way by passing the argument as list.

I'm late but
- can you check this #3

test the branch changes locally and see if the issue is still there, I don't have access to my Linux machine right now so I can't manually test it, since the package is relatively small I might write tests in the future

**Comment by EchoEllet** [comment]
> And when saving the image file, it should use `cp` (copying) rather than `mv` (moving), because currently, the image from the editor disappears after save and it will throw an 'asset not found' error.

I'm still not sure but is it because the user picked an image from his/her personal files and and the editor used it in the `Document` and we moved it from the personal files to somewhere else, I think we should not change move or delete any personal files on desktop because it's not in the sandbox system files like mobile apps

I already mentioned this in flutter quill in the last year but I'm not sure why I used `mv` over `cp`
in fact I'm not sure why I executing Linux commands in this dart plugin, I remember there was a reason prevent me from using the `dart:io` to interact with files directly, but it almost make the the plugin with no purpose

**Comment by Muhammed-Rahif** [comment]
> I'm still not sure but is it because the user picked an image from his/her personal files and and the editor used it in the Document and we moved it from the personal files to somewhere else.

Yes that is the case.

> but I'm not sure why I used `mv` over `cp`.

I see no advantage using `mv` over `cp` other than saving some space on storage.

> in fact I'm not sure why I executing Linux commands in this dart plugin

As long as things works, it doesn't matter to me.

**Comment by EchoEllet** [comment]
Can you test the new branch that fixes this issue?

**Comment by Muhammed-Rahif** [comment]
@ellet0 will you consider using `cp`?
